import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';
import SessionProviderUseClient from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/authOptions';
import CartContextProvider from '@/components/CartContext';
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({variable: '--font-geist-mono', subsets: ['latin']});

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app',};

//prettier-ignore
export default async function RootLayout({children,}: { children: React.ReactNode;}) {

    const session = await getServerSession(authOptions)

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Toaster></Toaster>
				<SessionProviderUseClient session={session}>
					<CartContextProvider>
						<div className="h-[100vh] flex flex-col bg-[#171615]">
							<div className="flex flex-[1]">
								<Navbar></Navbar>
							</div>
							<div className="flex flex-[14] overflow-y-scroll">
								{children}
							</div>
						</div>
					</CartContextProvider>
				</SessionProviderUseClient>
			</body>
		</html>
	);
}

